# Jules launch commands generated by /jules/dispatch.
# Review before running. This script starts remote Jules sessions.

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

Push-Location 'C:\aotp\projects\OracleV5'; Get-Content -Raw -LiteralPath 'C:\Users\abdul\.jules\jules_inbox\jules_dispatch\JT-024-389f1d-add-test-for-heartbeatmonitor-isalive.md' | jules new; Pop-Location
Push-Location 'C:\aotp\projects\OracleV5'; Get-Content -Raw -LiteralPath 'C:\Users\abdul\.jules\jules_inbox\jules_dispatch\JT-025-9e80e5-add-test-for-vixmonitor-reset.md' | jules new; Pop-Location
Push-Location 'C:\aotp\projects\OracleV5'; Get-Content -Raw -LiteralPath 'C:\Users\abdul\.jules\jules_inbox\jules_dispatch\JT-001-bbe920-add-test-for-resetselectorcandidates.md' | jules new; Pop-Location
Push-Location 'C:\aotp\projects\OracleV5'; Get-Content -Raw -LiteralPath 'C:\Users\abdul\.jules\jules_inbox\jules_dispatch\JT-002-39436e-serial-execution-of-asynchronous-file-i-o.md' | jules new; Pop-Location
Push-Location 'C:\aotp\projects\OracleV5'; Get-Content -Raw -LiteralPath 'C:\Users\abdul\.jules\jules_inbox\jules_dispatch\JT-003-9b62c7-add-test-for-volregimedetector-reset.md' | jules new; Pop-Location
Push-Location 'C:\aotp\projects\OracleV5'; Get-Content -Raw -LiteralPath 'C:\Users\abdul\.jules\jules_inbox\jules_dispatch\JT-006-857c83-add-test-for-secondssincelastpulse.md' | jules new; Pop-Location
