# Jules launch commands generated by /jules/dispatch.
# Review before running. This script starts remote Jules sessions.

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

Push-Location 'C:\Users\abdul\jules-bridge'; Get-Content -Raw -LiteralPath 'C:\Users\abdul\jules-bridge\jules_inbox\jules_dashboard_cloud_panel_dispatch\JT-001-0a1bb7-code-health-for-dashboard-ui-src-app-jsx-dashboard-ui-src-in.md' | jules new; Pop-Location
