# Jules launch commands generated by /jules/dispatch.
# Review before running. This script starts remote Jules sessions.

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

Push-Location 'C:\Users\abdul\jules-bridge'; Get-Content -Raw -LiteralPath 'jules_inbox\jules_provider_readiness_dispatch_strict\JT-001-99dce4-code-health-for-modules-health-service-py-modules-chat-servi.md' | jules new; Pop-Location
