# Jules launch commands generated by /jules/dispatch.
# Review before running. This script starts remote Jules sessions.

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

Push-Location 'C:\Users\abdul\jules-bridge'; Get-Content -Raw -LiteralPath 'C:\Users\abdul\jules-bridge\jules_inbox\jules_vm_chat_fallback_dispatch\JT-001-a7d59b-make-bridge-chat-production-ready-by-rotating-openrouter-api.md' | jules new; Pop-Location
