# Jules launch commands generated by /jules/dispatch.
# Review before running. This script starts remote Jules sessions.

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

Push-Location 'C:\Users\abdul\jules-bridge'; Get-Content -Raw -LiteralPath 'C:\Users\abdul\jules-bridge\jules_inbox\jules_dashboard_vm_fallback_ui_dispatch\JT-001-0a7ebc-surface-vm-worker-fallback-readiness-in-the-dashboard-header.md' | jules new; Pop-Location
